FROM python:3.12-alpine
USER root

RUN apk add --no-cache \
    build-base \
    mariadb-dev \
    pkgconfig \
    linux-headers \
    musl-dev \
    bash

COPY requirements.txt /code/requirements.txt
RUN set -ex \
    # 安装python库
    && pip3 install --upgrade pip \
    && pip3 install -r /code/requirements.txt \